### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by Venoox**
I added Dockerfile for easier development. Later I will also add Dockerfile for pogify-functions and then I will add instructions with example docker compose.

### CODE REVIEW

**Comment by jeongY-Cho** [comment]
Hi venoox thanks for contributing. But may i ask what the point of this dockerfile is? If its just copying files into a docker container then running it, its no different than anyone just doing the same on their computer without a container right? Am I missing something?

**Comment by Venoox** [comment]
I want to make creating dev environment easier by making Dockerfiles for each component and then one docker-compose that builds everything so people that want to contribute can do it easily.

**Comment by jeongY-Cho** [comment]
But if the docker file only copies files once isn't it then more difficult in this instance specifically. I understand how it can simplify the bootstrapping pogify-functions because of all the setup with the emulator and all but here don't people need to build a new image every time they make a change? At least that's what it looks like since it doesn't expose any of the files to edit? Is there something around this that I don't know about?

**Comment by Venoox** [comment]
When running the container you can mount a volume and that will make hot reloading possible

**Comment by jeongY-Cho** [comment]
Whats the process for doing that? Is it just as easy as cloning the repo and running it without a container? Sorry for all the questions im not an expert in docker

**Comment by Venoox** [comment]
For example like this `docker run -p 3000:3000 -v $PWD:/app pogify` but if you include all Dockerfiles together in one docker-compose file then it becomes as easy as `docker-compose up --build`

**Comment by jeongY-Cho** [comment]
Cool sounds good to me.

**Pull request merged**
